
CAPS_WORD_ENABLE = yes
# TAP_DANCE_ENABLE = yes
TAP_DANCE_ENABLE = no
RGBLIGHT_ENABLE = yes

AUDIO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ENCODER_ENABLE = no

MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
BACKLIGHT_ENABLE = no
DEBUG_ENABLE = no

RGBLIGHT_ENABLE = yes
RGBLIGHT_EFFECT_ALTERNATING = no
RGBLIGHT_EFFECT_BREATHING = no
RGBLIGHT_EFFECT_CHRISTMAS = no
RGBLIGHT_EFFECT_KNIGHT = no
RGBLIGHT_EFFECT_RAINBOW_MOOD = no
RGBLIGHT_EFFECT_RAINBOW_SWIRL = no
RGBLIGHT_EFFECT_RGB_TEST = no
RGBLIGHT_EFFECT_SNAKE = no
RGBLIGHT_EFFECT_STATIC_GRADIENT = no
RGBLIGHT_EFFECT_TWINKLE = no
